import type { RemoteContentBundle } from "../types/content";

const now = "2026-04-26T00:00:00.000Z";

export const seedContentBundle: RemoteContentBundle = {
  appConfig: {
    id: "default",
    minimumAppVersion: "0.1.0",
    contentVersion: 8,
    maintenanceMode: false,
    defaultLanguage: "tr",
    defaultCity: "İstanbul",
    forceUpdateMessage: "Sükût'u kullanmaya devam etmek için uygulamayı güncellemen gerekiyor.",
    maintenanceMessage: "Sükût kısa bir bakım molasında. Lütfen biraz sonra tekrar dene.",
    featureFlags: {
      premiumEnabled: false,
      paywallEnabled: true,
      weeklyReflectionEnabled: true,
      advancedDailyPlanEnabled: true,
      premiumThemesEnabled: false,
      remoteContentEnabled: false,
      localNotificationsEnabled: true,
      optionalAuthPlaceholder: true
    },
    paywallEnabled: true,
    premiumPricing: {
      monthlyLabel: "99 TL / ay",
      yearlyLabel: "799 TL / yıl",
      yearlyMonthlyEquivalentLabel: "Aylık yaklaşık 66 TL",
      highlightedPlan: "yearly"
    },
    isActive: true,
    createdAt: now,
    updatedAt: now
  },
  categories: [
    { id: "cat-dua-huzur", name: "Huzur Duaları", type: "dua", iconKey: "leaf", order: 1, isActive: true, createdAt: now, updatedAt: now },
    { id: "cat-dua-sukur", name: "Şükür ve Hamd", type: "dua", iconKey: "sun", order: 2, isActive: true, createdAt: now, updatedAt: now },
    { id: "cat-dua-sabir", name: "Sabır ve Ferahlık", type: "dua", iconKey: "horizon", order: 3, isActive: true, createdAt: now, updatedAt: now },
    { id: "cat-dua-korunma", name: "Korunma ve Teslimiyet", type: "dua", iconKey: "shield", order: 4, isActive: true, createdAt: now, updatedAt: now },
    { id: "cat-dua-af", name: "Af ve Arınma", type: "dua", iconKey: "water", order: 5, isActive: true, createdAt: now, updatedAt: now },
    { id: "cat-zikr-gunluk", name: "Günlük Zikir", type: "zikr", iconKey: "sparkle", order: 10, isActive: true, createdAt: now, updatedAt: now },
    { id: "cat-zikr-sabah", name: "Sabah Sükûneti", type: "zikr", iconKey: "sunrise", order: 11, isActive: true, createdAt: now, updatedAt: now },
    { id: "cat-zikr-aksam", name: "Akşam Sükûneti", type: "zikr", iconKey: "moon", order: 12, isActive: true, createdAt: now, updatedAt: now },
    { id: "cat-zikr-teslimiyet", name: "Teslimiyet", type: "zikr", iconKey: "hand", order: 13, isActive: true, createdAt: now, updatedAt: now }
  ],
  sources: [
    { id: "src-quran-bakara-201", title: "Bakara 201", type: "quran", citation: "Bakara Suresi 201. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/Bakara-suresi/208/201-ayet-tefsiri", note: "Dünya ve ahiret iyiliği duası.", locale: "tr", order: 1, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-quran-taha-25", title: "Tâhâ 25", type: "quran", citation: "Tâhâ Suresi 25. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/T%C3%A2h%C3%A2-suresi/2373/25-ayet-tefsiri", note: "Ferahlık ve iç açıklığı duası.", locale: "tr", order: 2, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-quran-taha-114", title: "Tâhâ 114", type: "quran", citation: "Tâhâ Suresi 114. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/T%C3%A2h%C3%A2-suresi/2462/114-ayet-tefsiri", note: "İlim artışı duası.", locale: "tr", order: 3, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-quran-enbiya-83", title: "Enbiyâ 83", type: "quran", citation: "Enbiyâ Suresi 83. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/Enbiy%C3%A2-suresi/2566/83-ayet-tefsiri", note: "Sıkıntı anında Hz. Eyyûb duası.", locale: "tr", order: 4, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-quran-enbiya-87", title: "Enbiyâ 87", type: "quran", citation: "Enbiyâ Suresi 87. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/Enbiy%C3%A2-suresi/2570/87-ayet-tefsiri", note: "Hz. Yûnus duası.", locale: "tr", order: 5, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-quran-neml-19", title: "Neml 19", type: "quran", citation: "Neml Suresi 19. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/Neml-suresi/3178/19-ayet-tefsiri", note: "Şükür duası.", locale: "tr", order: 6, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-quran-ali-imran-8", title: "Âl-i İmrân 8", type: "quran", citation: "Âl-i İmrân Suresi 8. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/%C3%82l-i%20%C4%B0mr%C3%A2n-suresi/301/8-ayet-tefsiri", note: "Kalbin doğruluk üzere kalması duası.", locale: "tr", order: 7, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-quran-ibrahim-40", title: "İbrâhîm 40", type: "quran", citation: "İbrâhîm Suresi 40. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/%C4%B0br%C3%A2h%C3%AEm-suresi/1790/40-ayet-tefsiri", note: "Namazı diri tutma duası.", locale: "tr", order: 8, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-quran-muminun-29", title: "Mü'minûn 29", type: "quran", citation: "Mü'minûn Suresi 29. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/M%C3%BC'min%C3%BBn-suresi/2690/29-ayet-tefsiri", note: "Bereketli konaklama duası.", locale: "tr", order: 9, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-quran-hashr-10", title: "Haşr 10", type: "quran", citation: "Haşr Suresi 10. ayet", url: "https://kuran.diyanet.gov.tr/tefsir/Ha%C5%9Fr-suresi/5134/10-ayet-tefsiri", note: "Mümin kardeşler için bağışlanma duası.", locale: "tr", order: 10, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-hadith-subhanallahi-bihamdihi", title: "Sübhânallahi ve bihamdihî", type: "hadith", citation: "Buhârî, Deavât, 65; Müslim, Zikir, 28", note: "Kısa tesbih zikri kaynağı.", locale: "tr", order: 11, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-hadith-la-havle", title: "Lâ havle zikri", type: "hadith", citation: "Buhârî, Deavât, 50; Müslim, Zikir, 44", note: "Teslimiyet zikri kaynağı.", locale: "tr", order: 12, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-hadith-asmaul-husna", title: "Esmâ-i Hüsnâ", type: "hadith", citation: "Buhârî, Şürût, 18; Müslim, Zikir, 5", note: "Allah'ın güzel isimleriyle dua bağlamı.", locale: "tr", order: 13, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-tdv-dua", title: "TDV İslâm Ansiklopedisi - Dua", type: "tdv", citation: "TDV İslâm Ansiklopedisi, Dua maddesi", url: "https://islamansiklopedisi.org.tr/dua", note: "Dua kavramı için editöryal arka plan.", locale: "tr", order: 14, isActive: true, createdAt: now, updatedAt: now },
    { id: "src-tdv-zikir", title: "TDV İslâm Ansiklopedisi - Zikir", type: "tdv", citation: "TDV İslâm Ansiklopedisi, Zikir maddesi", url: "https://islamansiklopedisi.org.tr/zikir", note: "Zikir kavramı için editöryal arka plan.", locale: "tr", order: 15, isActive: true, createdAt: now, updatedAt: now }
  ],
  duas: [
    {
      id: "dua-rabbena-atina",
      title: "Rabbena Atina",
      arabicText: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
      transliterationTr: "Rabbenâ âtinâ fid-dünyâ haseneten ve fil-âhireti haseneten ve kınâ azâben-nâr.",
      meaningTr: "Rabbimiz, bize dünyada da iyilik ver, ahirette de iyilik ver ve bizi ateş azabından koru.",
      categoryId: "cat-dua-huzur",
      moodTags: ["seekingPeace", "grateful", "undecided"],
      source: "Bakara Suresi 201. ayet",
      isPremium: false,
      order: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-ferahlik",
      title: "Ferahlık Duası",
      arabicText: "رَبِّ اشْرَحْ لِي صَدْرِي",
      transliterationTr: "Rabbişrah lî sadrî.",
      meaningTr: "Rabbim, göğsümü genişlet, gönlüme ferahlık ver.",
      categoryId: "cat-dua-sabir",
      moodTags: ["stressed", "sad", "focused"],
      source: "Tâhâ Suresi 25. ayet",
      isPremium: false,
      order: 2,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-ilim-arttir",
      title: "İlmimi Artır",
      arabicText: "رَبِّ زِدْنِي عِلْمًا",
      transliterationTr: "Rabbi zidnî ilmâ.",
      meaningTr: "Rabbim, ilmimi artır.",
      categoryId: "cat-dua-huzur",
      moodTags: ["focused", "undecided"],
      source: "Tâhâ Suresi 114. ayet",
      isPremium: false,
      order: 3,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-zulmettim",
      title: "Nefsime Zulmettim",
      arabicText: "رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي",
      transliterationTr: "Rabbi innî zalemtü nefsî fağfir lî.",
      meaningTr: "Rabbim, ben nefsime zulmettim; beni bağışla.",
      categoryId: "cat-dua-af",
      moodTags: ["sad", "seekingPeace"],
      source: "Kasas Suresi 16. ayet",
      isPremium: false,
      order: 4,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-eyyub",
      title: "Sıkıntı Anında Dua",
      arabicText: "أَنِّي مَسَّنِيَ الضُّرُّ وَأَنْتَ أَرْحَمُ الرَّاحِمِينَ",
      transliterationTr: "Ennî messeniyed-durru ve ente erhamür-râhimîn.",
      meaningTr: "Bana bir sıkıntı dokundu; Sen merhametlilerin en merhametlisisin.",
      categoryId: "cat-dua-sabir",
      moodTags: ["sad", "afraid", "stressed"],
      source: "Enbiyâ Suresi 83. ayet",
      isPremium: false,
      order: 5,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-yunus",
      title: "Teslimiyet Duası",
      arabicText: "لَا إِلٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
      transliterationTr: "Lâ ilâhe illâ ente sübhâneke innî küntü minez-zâlimîn.",
      meaningTr: "Senden başka ilâh yoktur. Seni tenzih ederim. Ben gerçekten yanlış yapanlardan oldum.",
      categoryId: "cat-dua-af",
      moodTags: ["afraid", "sad", "seekingPeace"],
      source: "Enbiyâ Suresi 87. ayet",
      isPremium: false,
      order: 6,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-sukur",
      title: "Şükre Yönelten Dua",
      arabicText: "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ",
      transliterationTr: "Rabbi evzi'nî en eşküre ni'metek.",
      meaningTr: "Rabbim, bana verdiğin nimete şükretmeyi gönlüme ilham et.",
      categoryId: "cat-dua-sukur",
      moodTags: ["grateful", "seekingPeace"],
      source: "Neml Suresi 19. ayet",
      isPremium: false,
      order: 7,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-korku-teslimiyet",
      title: "Bize Allah Yeter",
      arabicText: "حَسْبُنَا اللّٰهُ وَنِعْمَ الْوَكِيلُ",
      transliterationTr: "Hasbünallâhu ve ni'mel vekîl.",
      meaningTr: "Allah bize yeter; O ne güzel vekildir.",
      categoryId: "cat-dua-korunma",
      moodTags: ["afraid", "stressed", "undecided"],
      source: "Âl-i İmrân Suresi 173. ayet",
      isPremium: false,
      order: 8,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-sabir",
      title: "Sabır ve Sebat Duası",
      arabicText: "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا",
      transliterationTr: "Rabbenâ efriğ aleynâ sabran ve sebbit akdâmenâ.",
      meaningTr: "Rabbimiz, üzerimize sabır dök ve ayaklarımızı sabit kıl.",
      categoryId: "cat-dua-sabir",
      moodTags: ["stressed", "afraid", "focused"],
      source: "Bakara Suresi 250. ayet",
      isPremium: false,
      order: 9,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-rahmet",
      title: "Rahmet ve Doğruluk Duası",
      arabicText: "رَبَّنَا آتِنَا مِنْ لَدُنْكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا",
      transliterationTr: "Rabbenâ âtinâ min ledünke rahmeten ve hey li lenâ min emrinâ raşedâ.",
      meaningTr: "Rabbimiz, katından bize rahmet ver ve işimizde bize doğruluk hazırla.",
      categoryId: "cat-dua-huzur",
      moodTags: ["undecided", "seekingPeace", "afraid"],
      source: "Kehf Suresi 10. ayet",
      isPremium: false,
      order: 10,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-kalbi-sabit-kil",
      title: "Kalbi Sabit Kılma Duası",
      arabicText: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً",
      transliterationTr: "Rabbenâ lâ tuziğ kulûbenâ ba'de iz hedeytenâ ve heb lenâ min ledünke rahmeh.",
      meaningTr: "Rabbimiz, bizi doğru yola ilettikten sonra kalplerimizi eğriltme; katından bize rahmet bağışla.",
      categoryId: "cat-dua-huzur",
      moodTags: ["undecided", "seekingPeace", "afraid"],
      source: "Âl-i İmrân Suresi 8. ayet",
      sourceReferenceIds: ["src-quran-ali-imran-8"],
      isPremium: false,
      order: 11,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-namazda-devam",
      title: "Namazda Devam Duası",
      arabicText: "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِنْ ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ",
      transliterationTr: "Rabbi'c'alnî mukîme's-salâti ve min zürriyyetî rabbenâ ve tekabbel duâ.",
      meaningTr: "Rabbim, beni ve soyumdan gelecekleri namazı özenle sürdürenlerden eyle; Rabbimiz, duamı kabul buyur.",
      categoryId: "cat-dua-huzur",
      moodTags: ["focused", "seekingPeace"],
      source: "İbrâhîm Suresi 40. ayet",
      sourceReferenceIds: ["src-quran-ibrahim-40"],
      isPremium: false,
      order: 12,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-bereketli-yol",
      title: "Bereketli Yol Duası",
      arabicText: "رَبِّ أَنْزِلْنِي مُنْزَلًا مُبَارَكًا وَأَنْتَ خَيْرُ الْمُنْزِلِينَ",
      transliterationTr: "Rabbi enzilnî münzelen mübâraken ve ente hayrul münzilîn.",
      meaningTr: "Rabbim, beni bereketli bir yere indir; Sen konuk edenlerin en hayırlısısın.",
      categoryId: "cat-dua-korunma",
      moodTags: ["afraid", "undecided", "seekingPeace"],
      source: "Mü'minûn Suresi 29. ayet",
      sourceReferenceIds: ["src-quran-muminun-29"],
      isPremium: false,
      order: 13,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-kardeslik",
      title: "Kardeşlik ve Arınma Duası",
      arabicText: "رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ",
      transliterationTr: "Rabbenâğfir lenâ ve li ihvâninellezîne sebekûnâ bil îmân.",
      meaningTr: "Rabbimiz, bizi ve imanda bizden önce gelen kardeşlerimizi bağışla.",
      categoryId: "cat-dua-af",
      moodTags: ["sad", "grateful", "seekingPeace"],
      source: "Haşr Suresi 10. ayet",
      sourceReferenceIds: ["src-quran-hashr-10"],
      isPremium: false,
      order: 14,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-merhamet-ve-af",
      title: "Merhamet ve Af Duası",
      arabicText: "رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ",
      transliterationTr: "Rabbığfir verham ve ente hayrur râhimîn.",
      meaningTr: "Rabbim, bağışla ve merhamet et; Sen merhamet edenlerin en hayırlısısın.",
      categoryId: "cat-dua-af",
      moodTags: ["sad", "seekingPeace"],
      source: "Mü'minûn Suresi 118. ayet",
      isPremium: false,
      order: 15,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-dogru-yol",
      title: "Doğru Yola Yöneliş Duası",
      arabicText: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
      transliterationTr: "İhdina's-sırâtal müstakîm.",
      meaningTr: "Bizi dosdoğru yola ilet.",
      categoryId: "cat-dua-huzur",
      moodTags: ["undecided", "focused", "seekingPeace"],
      source: "Fâtiha Suresi 6. ayet",
      isPremium: false,
      order: 16,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-aile-huzuru",
      title: "Aile ve Göz Aydınlığı Duası",
      arabicText: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ",
      transliterationTr: "Rabbenâ heb lenâ min ezvâcinâ ve zürriyyâtinâ kurrate a'yun.",
      meaningTr: "Rabbimiz, eşlerimizden ve çocuklarımızdan bize göz aydınlığı bağışla.",
      categoryId: "cat-dua-sukur",
      moodTags: ["grateful", "seekingPeace"],
      source: "Furkan Suresi 74. ayet",
      isPremium: false,
      order: 17,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "dua-korunma-vesvese",
      title: "Vesveseden Korunma Duası",
      arabicText: "رَبِّ أَعُوذُ بِكَ مِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَعُوذُ بِكَ رَبِّ أَنْ يَحْضُرُونِ",
      transliterationTr: "Rabbi eûzü bike min hemezâti'ş-şeyâtîn ve eûzü bike rabbi en yahdurûn.",
      meaningTr: "Rabbim, şeytanların kışkırtmalarından Sana sığınırım; onların yanımda bulunmalarından da Sana sığınırım.",
      categoryId: "cat-dua-korunma",
      moodTags: ["afraid", "stressed"],
      source: "Mü'minûn Suresi 97-98. ayetler",
      isPremium: false,
      order: 18,
      isActive: true,
      createdAt: now,
      updatedAt: now
    }
  ],
  zikrs: [
    { id: "zikr-subhanallah", title: "Sübhanallah", text: "Sübhanallah", recommendedCount: 33, description: "Günü sade bir farkındalıkla yavaşlatmak için kısa bir zikir.", categoryId: "cat-zikr-gunluk", source: "Buhârî, Ezân, 155; Müslim, Mesâcid, 146", order: 1, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-elhamdulillah", title: "Elhamdülillah", text: "Elhamdülillah", recommendedCount: 33, description: "Şükür duygusunu diri tutan yalın bir hatırlama.", categoryId: "cat-zikr-gunluk", source: "Buhârî, Ezân, 155; Müslim, Mesâcid, 146", order: 2, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-allahu-ekber", title: "Allahu Ekber", text: "Allahu Ekber", recommendedCount: 33, description: "Günün telaşında ölçüyü ve tevazuyu hatırlatır.", categoryId: "cat-zikr-gunluk", source: "Buhârî, Ezân, 155; Müslim, Mesâcid, 146", order: 3, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-hasbunallah", title: "Hasbünallah", text: "Hasbünallahu ve ni'mel vekîl", recommendedCount: 33, description: "Kaygı anlarında teslimiyet duygusunu hatırlatır.", categoryId: "cat-zikr-teslimiyet", source: "Âl-i İmrân Suresi 173. ayet", order: 4, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-la-havle", title: "La Havle", text: "Lâ havle ve lâ kuvvete illâ billâh", recommendedCount: 33, description: "Güç ve kuvvetin Allah'tan olduğunu hatırlatan sakin bir zikir.", categoryId: "cat-zikr-teslimiyet", source: "Buhârî, Deavât, 50; Müslim, Zikir, 44", order: 5, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-istiğfar", title: "Estağfirullah", text: "Estağfirullah", recommendedCount: 100, description: "Günün sonunda kalbi arındırmaya niyet eden kısa bir istiğfar.", categoryId: "cat-zikr-aksam", source: "Müslim, Zikir, 41", order: 6, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-salat", title: "Salavat", text: "Allahümme salli alâ seyyidinâ Muhammed", recommendedCount: 10, description: "Cuma ve sakin okuma zamanları için kısa salavat.", categoryId: "cat-zikr-gunluk", source: "Ahzâb Suresi 56. ayet", order: 7, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-tevhid", title: "Tevhid", text: "Lâ ilâhe illallah", recommendedCount: 33, description: "Kalbi sade bir merkeze çağıran temel zikir.", categoryId: "cat-zikr-sabah", source: "Müslim, Îmân, 46", order: 8, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-subhanallahi-bihamdihi", title: "Sübhânallahi ve Bihamdihî", text: "Sübhânallahi ve bihamdihî", recommendedCount: 100, description: "Günü kısa ve derin bir tesbihle yumuşatmak için sade bir zikir.", categoryId: "cat-zikr-gunluk", source: "Buhârî, Deavât, 65; Müslim, Zikir, 28", sourceReferenceIds: ["src-hadith-subhanallahi-bihamdihi"], order: 9, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-la-ilahe-vahdehu", title: "Tevhid ve Hamd", text: "Lâ ilâhe illallahu vahdehû lâ şerîke leh", recommendedCount: 10, description: "Sabah veya akşam kısa bir tevhid hatırlaması için.", categoryId: "cat-zikr-sabah", source: "Buhârî, Deavât, 64; Müslim, Zikir, 28", order: 10, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-ya-hayyu", title: "Ya Hayyu Ya Kayyum", text: "Yâ Hayyu yâ Kayyûm, bi rahmetike esteğîs", recommendedCount: 7, description: "Daralan anlarda Allah'ın diri ve kayyum oluşunu hatırlatan kısa niyaz.", categoryId: "cat-zikr-teslimiyet", source: "Tirmizî, Deavât, 91", order: 11, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-allahumme-afuvvun", title: "Af Duası", text: "Allahümme inneke afüvvün tuhibbul afve fa'fu annî", recommendedCount: 7, description: "Af ve arınma niyetiyle okunabilecek kısa dua-zikir.", categoryId: "cat-zikr-aksam", source: "Tirmizî, Deavât, 84", order: 12, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-rabbighfir-li", title: "Rabbığfir Lî", text: "Rabbığfir lî", recommendedCount: 33, description: "Kalbi sade bir istiğfar cümlesine döndüren kısa tekrar.", categoryId: "cat-zikr-aksam", source: "Kur'an ve sünnette istiğfar vurgusu", order: 13, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-esma-rahman", title: "Ya Rahmân Ya Rahîm", text: "Yâ Rahmân, Yâ Rahîm", recommendedCount: 33, description: "Merhamet duygusunu hatırlatan esma zikri.", categoryId: "cat-zikr-gunluk", source: "Esmâ-i Hüsnâ geleneği", sourceReferenceIds: ["src-hadith-asmaul-husna"], order: 14, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-esma-latif", title: "Ya Latîf", text: "Yâ Latîf", recommendedCount: 33, description: "Nazik ve ince bir yardım umuduyla okunabilecek sakin esma zikri.", categoryId: "cat-zikr-teslimiyet", source: "Esmâ-i Hüsnâ geleneği", sourceReferenceIds: ["src-hadith-asmaul-husna"], order: 15, isActive: true, createdAt: now, updatedAt: now },
    { id: "zikr-emanet", title: "Tevekkül Cümlesi", text: "Bismillâhi tevekkeltü alallah", recommendedCount: 7, description: "Güne başlarken niyeti Allah'a emanet etmeye yardımcı kısa hatırlama.", categoryId: "cat-zikr-sabah", source: "Ebû Dâvûd, Edeb, 102; Tirmizî, Deavât, 34", order: 16, isActive: true, createdAt: now, updatedAt: now }
  ],
  dailyContents: [
    { id: "daily-sukunet-1", date: "rotation-1", title: "Bugün kalbine yer aç", shortMessage: "Kısa bir dua, sakin bir nefes ve küçük bir iyilik bugün için yeterli bir başlangıç olabilir.", duaId: "dua-rabbena-atina", zikrId: "zikr-subhanallah", source: "Bakara Suresi 201. ayet", order: 1, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-sukur-2", date: "rotation-2", title: "Bugün şükrü fark et", shortMessage: "Günün içinde küçük bir nimeti fark edip şükür cümlesiyle kalbini yumuşat.", duaId: "dua-sukur", zikrId: "zikr-elhamdulillah", source: "Neml Suresi 19. ayet", order: 2, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-ferah-3", date: "rotation-3", title: "Daralan yere nefes bırak", shortMessage: "Bir şeyi hemen çözmek zorunda değilsin. Önce dur, sonra ferahlık duasını oku.", duaId: "dua-ferahlik", zikrId: "zikr-la-havle", source: "Tâhâ Suresi 25. ayet", order: 3, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-sabir-4", date: "rotation-4", title: "Sabrı küçük adımla başlat", shortMessage: "Bugün sabrı büyük sözlerle değil, sakin bir adımla taşı.", duaId: "dua-sabir", zikrId: "zikr-hasbunallah", source: "Bakara Suresi 250. ayet", order: 4, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-af-5", date: "rotation-5", title: "İçini temizleyen cümle", shortMessage: "Yanlışlarını fark etmek bir yük değil, dönüş için nazik bir kapı olabilir.", duaId: "dua-yunus", zikrId: "zikr-istiğfar", source: "Enbiyâ Suresi 87. ayet", order: 5, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-odak-6", date: "rotation-6", title: "Bugün zihnini toparla", shortMessage: "Kısa bir ilim duası ve sade bir niyet, dağınık günü toparlamaya eşlik edebilir.", duaId: "dua-ilim-arttir", zikrId: "zikr-tevhid", source: "Tâhâ Suresi 114. ayet", order: 6, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-rahmet-7", date: "rotation-7", title: "Yoluna rahmet iste", shortMessage: "Kararsızlıkta kesin cevap aramak yerine, doğruluğa yönelmek için dua et.", duaId: "dua-rahmet", zikrId: "zikr-allahu-ekber", source: "Kehf Suresi 10. ayet", order: 7, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-teslimiyet-8", date: "rotation-8", title: "Bugün teslimiyeti hatırla", shortMessage: "Kontrol edemediğin şeylerin yanında kalbini yormadan Allah'a güvenmeyi hatırla.", duaId: "dua-korku-teslimiyet", zikrId: "zikr-hasbunallah", source: "Âl-i İmrân Suresi 173. ayet", order: 8, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-sessiz-baslangic-9", date: "rotation-9", title: "Sessiz bir başlangıç", shortMessage: "Bugün büyük bir değişim değil, sadece sakin bir başlangıç yeterli olabilir.", duaId: "dua-rabbena-atina", zikrId: "zikr-tevhid", source: "Bakara Suresi 201. ayet; Müslim, Îmân, 46", order: 9, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-arinma-10", date: "rotation-10", title: "Arınmaya küçük bir kapı", shortMessage: "İstiğfarı yük gibi değil, kalbi hafifleten nazik bir dönüş olarak düşün.", duaId: "dua-zulmettim", zikrId: "zikr-istiğfar", source: "Kasas Suresi 16. ayet; Müslim, Zikir, 41", order: 10, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-sukur-11", date: "rotation-11", title: "Bir nimeti adlandır", shortMessage: "Bugün şükür için tek bir nimeti seç; onu fark etmek bile kalbi yumuşatabilir.", duaId: "dua-sukur", zikrId: "zikr-elhamdulillah", source: "Neml Suresi 19. ayet", order: 11, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-sabir-12", date: "rotation-12", title: "Sabrı acele ettirme", shortMessage: "Sabır bazen beklemek değil, kendine sertleşmeden doğru adımı korumaktır.", duaId: "dua-sabir", zikrId: "zikr-la-havle", source: "Bakara Suresi 250. ayet; Buhârî, Deavât, 50", order: 12, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-salavat-13", date: "rotation-13", title: "Güne salavatla yumuşaklık kat", shortMessage: "Kısa bir salavat, telaşın içinde kalbe nezaket ve hatırlama alanı açabilir.", duaId: "dua-rahmet", zikrId: "zikr-salat", source: "Ahzâb Suresi 56. ayet", order: 13, isActive: true, createdAt: now, updatedAt: now },
    { id: "daily-ferah-14", date: "rotation-14", title: "Daralan yere ferahlık iste", shortMessage: "Sıkışmış hissediyorsan önce bir nefes ver; sonra ferahlık duasını yavaşça oku.", duaId: "dua-ferahlik", zikrId: "zikr-subhanallah", source: "Tâhâ Suresi 25. ayet", order: 14, isActive: true, createdAt: now, updatedAt: now }
  ],
  moodContents: [
    { id: "mood-stressed", moodKey: "stressed", title: "Yavaşla ve nefesine dön", description: "Stresli anlarda kısa bir zikirle ritmini sakinleştirmek destek olabilir.", duaIds: ["dua-ferahlik", "dua-sabir"], zikrIds: ["zikr-la-havle", "zikr-hasbunallah"], shortAdvice: "Üç derin nefes al, sonra duayı yavaşça oku.", source: "Tâhâ Suresi 25. ayet; Bakara Suresi 250. ayet", order: 1, isActive: true, createdAt: now, updatedAt: now },
    { id: "mood-sad", moodKey: "sad", title: "Hüzne yumuşak bir alan aç", description: "Üzüntü anında kendini zorlamadan, kısa bir dua ile içini toparlamaya niyet edebilirsin.", duaIds: ["dua-eyyub", "dua-zulmettim"], zikrIds: ["zikr-istiğfar"], shortAdvice: "Bugün kendine sert davranmadan, sadece bir cümlelik dua oku.", source: "Enbiyâ Suresi 83. ayet; Kasas Suresi 16. ayet", order: 2, isActive: true, createdAt: now, updatedAt: now },
    { id: "mood-afraid", moodKey: "afraid", title: "Korkuda teslimiyeti hatırla", description: "Korkuyu yok saymadan, kalbi güvene çağıran kısa bir teslimiyet cümlesi seç.", duaIds: ["dua-korku-teslimiyet", "dua-yunus"], zikrIds: ["zikr-hasbunallah"], shortAdvice: "Korkuyu bastırmadan, 'Allah bana yeter' anlamını yavaşça düşün.", source: "Âl-i İmrân Suresi 173. ayet; Enbiyâ Suresi 87. ayet", order: 3, isActive: true, createdAt: now, updatedAt: now },
    { id: "mood-undecided", moodKey: "undecided", title: "Kararsızlıkta doğruluk iste", description: "Her şeyi hemen bilmek zorunda değilsin; doğru olana yönelmek için küçük bir dua yeterli olabilir.", duaIds: ["dua-rahmet", "dua-ilim-arttir"], zikrIds: ["zikr-tevhid"], shortAdvice: "Bir karar için önce niyetini sadeleştir, sonra küçük bir adım seç.", source: "Kehf Suresi 10. ayet; Tâhâ Suresi 114. ayet", order: 4, isActive: true, createdAt: now, updatedAt: now },
    { id: "mood-grateful", moodKey: "grateful", title: "Şükrü görünür kıl", description: "Şükretmek istediğinde bir nimeti adlandır ve onu küçük bir iyilikle tamamla.", duaIds: ["dua-sukur", "dua-rabbena-atina"], zikrIds: ["zikr-elhamdulillah"], shortAdvice: "Bugün şükrettiğin bir şeyi not et ve içinden hamd et.", source: "Neml Suresi 19. ayet; Bakara Suresi 201. ayet", order: 5, isActive: true, createdAt: now, updatedAt: now },
    { id: "mood-peace", moodKey: "seekingPeace", title: "Huzuru küçük bir niyetle başlat", description: "Günün içinde kısa bir duraklama bile kalbe iyi gelebilir.", duaIds: ["dua-rabbena-atina", "dua-rahmet"], zikrIds: ["zikr-subhanallah"], shortAdvice: "Telefonu bırakıp bir dakika sessiz kalmayı dene.", source: "Bakara Suresi 201. ayet; Buhârî, Ezân, 155", order: 6, isActive: true, createdAt: now, updatedAt: now },
    { id: "mood-focused", moodKey: "focused", title: "Odak için sadeleş", description: "Dağınık zihni toparlamak için kısa bir dua, az hedef ve küçük süre yeterli olabilir.", duaIds: ["dua-ilim-arttir", "dua-ferahlik"], zikrIds: ["zikr-tevhid"], shortAdvice: "Bir işi seç, on dakika sadece ona dön.", source: "Tâhâ Suresi 114. ayet; Tâhâ Suresi 25. ayet", order: 7, isActive: true, createdAt: now, updatedAt: now }
  ],
  badges: [
    { id: "badge-first-zikr", name: "İlk Zikir", description: "İlk zikir hedefini başlattın.", iconKey: "breath", conditionType: "firstZikr", targetValue: 1, order: 1, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-seven-days", name: "7 Gün Devam", description: "Yedi gün boyunca küçük bir ritmi korudun.", iconKey: "path", conditionType: "streakDays", targetValue: 7, order: 2, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-first-favorite", name: "İlk Favori", description: "İlk duanı favorilerine ekledin.", iconKey: "bookmark", conditionType: "firstFavorite", targetValue: 1, order: 3, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-daily-intention", name: "Günün Niyeti", description: "Bir günde birden fazla küçük niyeti tamamladın.", iconKey: "intention", conditionType: "dailyGoals", targetValue: 2, order: 4, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-friday-rhythm", name: "Cuma Ritmi", description: "Cuma içeriğini sakin bir rutine bağladın.", iconKey: "friday", conditionType: "fridayRoutine", targetValue: 1, order: 5, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-fourteen-days", name: "14 Gün Sükûnet", description: "İki hafta boyunca ritmini korumaya devam ettin.", iconKey: "horizon", conditionType: "streakDays", targetValue: 14, order: 6, isPremium: true, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-night-calm", name: "Gece Sükûtu", description: "Akşam değerlendirme ritmini sürdürdün.", iconKey: "moon", conditionType: "dailyGoals", targetValue: 4, order: 7, isPremium: true, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-three-intentions", name: "Üç Niyet", description: "Bir günde üç sakin niyeti tamamladın.", iconKey: "sparkle", conditionType: "dailyGoals", targetValue: 3, order: 8, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-ten-days", name: "10 Gün Devam", description: "On günlük ritmini nazikçe korudun.", iconKey: "path", conditionType: "streakDays", targetValue: 10, order: 9, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-thirty-days", name: "30 Gün Sessiz İstikrar", description: "Otuz gün boyunca devam niyetini taşıdın.", iconKey: "crescent", conditionType: "streakDays", targetValue: 30, order: 10, isPremium: true, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-five-favorites", name: "Dua Seçkisi", description: "Beş duayı kendi sakin seçkine ekledin.", iconKey: "bookmark", conditionType: "firstFavorite", targetValue: 5, order: 11, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-zikr-rhythm", name: "Zikir Ritmi", description: "Zikir hedefini tamamlayarak güne ritim kattın.", iconKey: "breath", conditionType: "firstZikr", targetValue: 1, order: 12, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-five-intentions", name: "Beş Sakin Adım", description: "Bir günde beş niyeti tamamlayarak ritmini güçlendirdin.", iconKey: "steps", conditionType: "dailyGoals", targetValue: 5, order: 13, isPremium: true, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-full-day", name: "Tam Gün Sükûneti", description: "Günün tüm temel niyetlerini tamamladın.", iconKey: "circle", conditionType: "dailyGoals", targetValue: 6, order: 14, isPremium: true, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-twenty-one-days", name: "21 Gün Devam", description: "Üç haftalık sakin devam zincirini korudun.", iconKey: "path", conditionType: "streakDays", targetValue: 21, order: 15, isPremium: true, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-forty-days", name: "40 Gün İstikrar", description: "Uzun soluklu devam niyetini kırk güne taşıdın.", iconKey: "horizon", conditionType: "streakDays", targetValue: 40, order: 16, isPremium: true, isActive: true, createdAt: now, updatedAt: now },
    { id: "badge-ten-favorites", name: "Kalbe Yakın Seçki", description: "On içeriği favorilerine ekleyerek kendi okuma alanını kurdun.", iconKey: "bookmark", conditionType: "firstFavorite", targetValue: 10, order: 17, isActive: true, createdAt: now, updatedAt: now }
  ],
  events: [
    { id: "event-friday-salat", eventType: "friday", title: "Cuma Salavat Rutini", description: "Cuma günleri kısa salavat, sakin okuma ve kaynaklı bir dua önerisi.", startDate: "2026-01-01", endDate: "2026-12-31", suggestedDuaIds: ["dua-rabbena-atina", "dua-sukur"], suggestedZikrIds: ["zikr-salat", "zikr-elhamdulillah"], notificationTitle: "Cuma için nazik hatırlatma", notificationBody: "Bugün kısa bir salavat ve dua ile ritmini tazeleyebilirsin.", source: "Ahzâb Suresi 56. ayet; TDV İslâm Ansiklopedisi, Cuma maddesi", order: 1, isActive: true, createdAt: now, updatedAt: now },
    { id: "event-friday-kahf", eventType: "friday", title: "Cuma Sükûnet Okuması", description: "Cuma günü Kehf Suresi çevresinde kısa bir okuma niyeti ve teslimiyet zikri.", startDate: "2026-01-01", endDate: "2026-12-31", suggestedDuaIds: ["dua-rahmet"], suggestedZikrIds: ["zikr-hasbunallah"], notificationTitle: "Cuma okuması", notificationBody: "Bugün kısa bir okuma ve dua için birkaç dakika ayırabilirsin.", source: "Kehf Suresi 10. ayet; TDV İslâm Ansiklopedisi, Cuma maddesi", order: 2, isActive: true, createdAt: now, updatedAt: now },
    { id: "event-ramadan-general", eventType: "ramadan", title: "Ramazan Sakinliği", description: "Ramazan günlerinde dua, şükür ve ölçülü bir günlük niyet alanı.", startDate: "2026-02-18", endDate: "2026-03-19", suggestedDuaIds: ["dua-rabbena-atina", "dua-sukur"], suggestedZikrIds: ["zikr-elhamdulillah", "zikr-istiğfar"], notificationTitle: "Ramazan için sakin niyet", notificationBody: "Bugün dua, şükür ve küçük bir iyilik için alan açabilirsin.", source: "Bakara Suresi 183-185. ayetler", order: 3, isActive: true, createdAt: now, updatedAt: now },
    { id: "event-eid-general", eventType: "eid", title: "Bayram Şükrü", description: "Bayram günlerinde şükür, nezaket ve yakınlık duygusunu öne çıkaran kısa içerik.", startDate: "2026-03-20", endDate: "2026-03-22", suggestedDuaIds: ["dua-sukur", "dua-rabbena-atina"], suggestedZikrIds: ["zikr-elhamdulillah"], notificationTitle: "Bayram şükrü", notificationBody: "Bugün şükrü ve güzel sözü çoğaltmaya niyet edebilirsin.", source: "Neml Suresi 19. ayet", order: 4, isActive: true, createdAt: now, updatedAt: now },
    { id: "event-kandil-general", eventType: "kandil", title: "Kandil Gecesi İçin Sakin Alan", description: "Kandil gecelerinde istiğfar, dua ve sakin bir muhasebe için kısa öneri.", startDate: "2026-01-01", endDate: "2026-12-31", suggestedDuaIds: ["dua-yunus", "dua-zulmettim"], suggestedZikrIds: ["zikr-istiğfar"], notificationTitle: "Kandil için kısa hatırlatma", notificationBody: "Bu gece kısa bir dua ve istiğfar için sakin bir zaman ayırabilirsin.", source: "Enbiyâ Suresi 87. ayet; Kasas Suresi 16. ayet", order: 5, isActive: false, createdAt: now, updatedAt: now }
  ],
  notificationTemplates: [
    { id: "notification-daily-soft", title: "Kısa bir duraklama", body: "Bugünün duası ve zikri hazır.", type: "daily", order: 1, isActive: true, createdAt: now, updatedAt: now },
    { id: "notification-daily-sukur", title: "Bugün şükür alanı", body: "Bir nimeti fark edip kısa bir hamd cümlesiyle günü yumuşatabilirsin.", type: "daily", order: 2, isActive: true, createdAt: now, updatedAt: now },
    { id: "notification-event-friday", title: "Cuma ritmi", body: "Kısa bir salavat, dua ve sakin okuma için birkaç dakika ayırabilirsin.", type: "event", order: 3, isActive: true, createdAt: now, updatedAt: now },
    { id: "notification-streak", title: "Küçük ritmini koru", body: "Bugünün niyetlerinden birini tamamlamak için nazik bir zaman.", type: "streak", order: 4, isActive: true, createdAt: now, updatedAt: now },
    { id: "notification-gentle", title: "Sakin hatırlatma", body: "Bir nefes, bir dua, bir küçük iyilik.", type: "gentleReminder", order: 5, isActive: true, createdAt: now, updatedAt: now }
  ],
  planTemplates: [
    {
      id: "plan-7-huzur",
      title: "7 Gün Huzur Planı",
      description: "Her gün kısa dua, zikir ve sakin bir niyetle ilerleyen temel plan.",
      durationDays: 7,
      isPremium: false,
      taskTitles: ["Günlük içeriği oku", "33 zikir tamamla", "Bir dua oku"],
      suggestedDuaIds: ["dua-rabbena-atina", "dua-ferahlik"],
      suggestedZikrIds: ["zikr-subhanallah", "zikr-elhamdulillah"],
      source: "Sükût plan şablonu",
      order: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "plan-14-sukunet",
      title: "14 Gün Sükûnet Planı",
      description: "Sabah ve akşam küçük ritimleri birleştiren daha derin alışkanlık planı.",
      durationDays: 14,
      isPremium: true,
      taskTitles: ["Sabah duası", "Günlük zikir", "Ruh hali seçimi", "Akşam değerlendirme"],
      suggestedDuaIds: ["dua-sukur", "dua-sabir", "dua-rahmet"],
      suggestedZikrIds: ["zikr-la-havle", "zikr-istiğfar"],
      source: "Sükût Ayrıcalık plan şablonu",
      order: 2,
      isActive: true,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "plan-30-devam",
      title: "30 Gün Devam Niyeti",
      description: "Devam zinciri, haftalık içgörü ve sessiz ödül koleksiyonuna bağlı uzun plan.",
      durationDays: 30,
      isPremium: true,
      taskTitles: ["Günlük plan", "Zikir hedefi", "Dua okuma", "Haftalık içgörü"],
      suggestedDuaIds: ["dua-rabbena-atina", "dua-yunus", "dua-sukur"],
      suggestedZikrIds: ["zikr-tevhid", "zikr-salat", "zikr-istiğfar"],
      source: "Sükût Ayrıcalık plan şablonu",
      order: 3,
      isActive: true,
      createdAt: now,
      updatedAt: now
    }
  ]
};
